### PR TITLE
Update Character.java

### PR DESCRIPTION
**Pull request by onsah**
please accept

### CODE REVIEW

**Review by MntShmrp — COMMENTED** [review]
For node: MovementStrategy comment: nn
Access it through, baseurl/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert

**Review by MntShmrp — COMMENTED** [review]
For node: Enemy comment: vvvv
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SineBouncingMovement
User's comment is: vvcvcvc
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SineBouncingMovement
User's comment is: fdsgfdgf
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: BouncingMovement
User's comment is: cccc
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: vvv
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: vcvc
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: try1
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: try2
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: PApplet
User's comment is: try3
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Character
User's comment is: <div>try4</div><div><br></div>
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: <div>envtry1</div>
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SineSideMovement
User's comment is: envtry2
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SineSideMovement
User's comment is: vdffdgd
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: dvfbfdgdfgs
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: dfjsdfhdsjf
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: fdgfdgdfs
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert/main)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: jsdhfjdhjgdf
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by AtaYurtsever — COMMENTED** [review]
For node: Character
User's comment is: abcdef
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by AtaYurtsever — COMMENTED** [review]
For node: Enemy
User's comment is: new comment<br>
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SideMovement
User's comment is: hhjjhj
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: BouncingMovement
User's comment is: Try private<br>
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SineSideMovement
User's comment is: jdfkjsdkfjkj
Access it through, [this link](http://localhost:3000/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SineBouncingMovement
User's comment is: Try1<br>
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Character
User's comment is: Try user1<br>
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SideMovement
User's comment is: Try1
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: Hey
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
User's comment is: User1<br>
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SideMovement
User's comment is: Comment1
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: SideMovement
User's comment is: Comment2
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
's comment is: Try Comment 1
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
MntShmrp's comment is: Try Comment 2
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
MntShmrp's comment is: Try3
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: PApplet
MntShmrp's comment is: Try 4
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
MntShmrp's comment is: Try6
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: Game
MntShmrp's comment is: Try7
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: MovementStrategy
MntShmrp's comment is: Hey
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: MovementStrategy
MntShmrp's comment is: Hey2
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by DilrubaSultan — COMMENTED** [review]
For node: MovementStrategy
DilrubaSultan's comment is: Dilruba's comment
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: MovementStrategy
MntShmrp's comment is: Mnts' comment
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: MovementStrategy
MntShmrp's comment is: Now I see both comments
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert)

**Review by DilrubaSultan — COMMENTED** [review]
For node: Game
DilrubaSultan's comment is: Let's see whether this still works
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/Game)

**Review by DilrubaSultan — COMMENTED** [review]
For node: Enemy
DilrubaSultan's comment is: Hey
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/Enemy)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineSideMovement
DilrubaSultan's comment is: Hey
Access it through, [this link](http://localhost:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineSideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by MntShmrp — COMMENTED** [review]
For node: PApplet
MntShmrp's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/PApplet)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Test2
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: MovementStrategy
DilrubaSultan's comment is: Continue
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/MovementStrategy)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineSideMovement
DilrubaSultan's comment is: test1
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineSideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineSideMovement
DilrubaSultan's comment is: tet3
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineSideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineSideMovement
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineSideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: Enemy
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/Enemy)

**Review by DilrubaSultan — COMMENTED** [review]
For node: PApplet
DilrubaSultan's comment is: hey
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/PApplet)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineSideMovement
DilrubaSultan's comment is: test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineSideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Test25
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineBouncingMovement
DilrubaSultan's comment is: test25
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineBouncingMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: Game
DilrubaSultan's comment is: test25
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/Game)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SineSideMovement
DilrubaSultan's comment is: Test25
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SineSideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: Game
DilrubaSultan's comment is: Test25-1
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/Game)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Test25-2
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: MovementStrategy
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/MovementStrategy)

**Review by DilrubaSultan — COMMENTED** [review]
For node: Game
DilrubaSultan's comment is: Try
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/Game)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: yyy
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Hmmmm67
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by MntShmrp — COMMENTED** [review]
For node: SideMovement
MntShmrp's comment is: Hey
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by MntShmrp — COMMENTED** [review]
For node: SideMovement
MntShmrp's comment is: Hey
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Review by DilrubaSultan — COMMENTED** [review]
For node: SideMovement
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Test/dertfile/124/MntsShrmp_Test_124_from_onsah-patch-1.dert/SideMovement)

**Comment by onsah** [comment]
:)

**Pull request closed without merging**
